# configuration de base de l'application
# server:
#  port: 9100
  
# configuration de h2
spring:
  h2:
    console:
      enabled: true
    path: /h2

# configuration datasource
  datasource:
    url:  jdbc:h2:mem:clientsDb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
